### ISSUE TITLE
UnsupportedDataFormatError: Unsupported texture format RGB565 (104)

### ISSUE THREAD

**Issue by JokerDKha** [Tyulis/3DSkit#25]
Help with Pokemon Ultra Sun And Moon bflim.
![image](https://user-images.githubusercontent.com/56380626/104073368-10e8aa00-5240-11eb-8b32-392ef3fba676.png)

**Comment by Tyulis** [comment]
That was a small error, it's fixed now. Thanks for you input !

**Comment by JokerDKha** [comment]
![image](https://user-images.githubusercontent.com/56380626/104705378-68a97880-574c-11eb-8a4d-96b4bf2c60c9.png)
Sorry for bothering you again, but how do I repack bflim to RGB565. I tried repack it many times but it shows RGBA8.
The Hex file is here.
Original File:
![image](https://user-images.githubusercontent.com/56380626/104705698-d2c21d80-574c-11eb-8757-3a55149cad21.png)
Pack File:
![image](https://user-images.githubusercontent.com/56380626/104705767-e8374780-574c-11eb-8ba4-79bd438ec9bc.png)

**Comment by Tyulis** [comment]
Did you use the `-O format=RGB565` command line option ?
Even if the texture is not is the original format, usually it doesn’t cause any problem anyway.

**Comment by IcySon55** [comment]
"Even if the texture is not is the original format, usually it doesn’t cause any problem anyway."

I would not recommend this. The game is using RGB565 for a reason, and that is VRAM. If you go around randomly increasing the size of textures and other images, you might crash the game if it runs out of memory. Then you'll be pulling your hair out trying to figure out what's going wrong!

**Comment by JokerDKha** [comment]
> Did you use the `-O format=RGB565` command line option ?
> Even if the texture is not is the original format, usually it doesn’t cause any problem anyway.

Now the pack is good but seem like is make picture error like this.
Im used: 3dskit.py -pf BFLIM -O format=RGB565
![image](https://user-images.githubusercontent.com/56380626/104809925-96152580-5823-11eb-9b56-9bb111e9524b.png)

**Comment by JokerDKha** [comment]
> "Even if the texture is not is the original format, usually it doesn’t cause any problem anyway."
> 
> I would not recommend this. The game is using RGB565 for a reason, and that is VRAM. If you go around randomly increasing the size of textures and other images, you might crash the game if it runs out of memory. Then you'll be pulling your hair out trying to figure out what's going wrong!

Yeah the game is crash if using file not RGB565.

**Comment by Tyulis** [comment]
> "Even if the texture is not is the original format, usually it doesn’t cause any problem anyway."
> 
> I would not recommend this. The game is using RGB565 for a reason, and that is VRAM. If you go around randomly increasing the size of textures and other images, you might crash the game if it runs out of memory. Then you'll be pulling your hair out trying to figure out what's going wrong!

You’re right, hence the "usually". I never got any problems with that, but this doesn’t mean it cannot happen. But it works with `-O format=RGB565`, I just got the time to double-check and resolved a small byte order problem by the way. 

> Now im the pack is good but seem like is make picture error like this.

If the latest commit doesn’t solve your problem, check that you use all the original options (`-O format=<format>` for the pixel format, `-O swizzle=<texture swizzling option>`), just as they are printed by the extraction command.

**Comment by JokerDKha** [comment]
It only pack single one output format like this.
It cant pack 2 -o
![image](https://user-images.githubusercontent.com/56380626/104810344-7cc1a880-5826-11eb-8016-896c7bb6ffca.png)

**Comment by Tyulis** [comment]
The packer-specific options are with an upper-case O
In this case, `3DSkit.py -pf BFLIM -O swizzle=4 -O format=RGB565`

**Comment by JokerDKha** [comment]
it still error like same way:
![image](https://user-images.githubusercontent.com/56380626/104810456-4173a980-5827-11eb-9c5e-5a0084fb47d9.png)
![image](https://user-images.githubusercontent.com/56380626/104810460-46d0f400-5827-11eb-9475-299e9c53a8df.png)

**Comment by Tyulis** [comment]
Oh, I see. I assume this file comes from a 3DS, so it must be little endian, but as BFLIM is originally a WiiU format, it is packed in big endian by default. You have to force little endian with the `-l` option

**Comment by JokerDKha** [comment]
still crashing a game and picture error
![image](https://user-images.githubusercontent.com/56380626/104811087-b943d300-582b-11eb-8218-a7fbd9875765.png)
![image](https://user-images.githubusercontent.com/56380626/104811091-bcd75a00-582b-11eb-871f-116825c401de.png)

**Comment by Tyulis** [comment]
Ok, I double-checked everything, indeed it causes a game crash but I have no problem with the image whatsoever, so the problem might be elsewhere. I’m trying to investigate this.

**Comment by Tyulis** [comment]
I finally found several problems with subdirectories in the GARC and ALYT packers, especially on Windows. It’s now fixed, and it works
![image](https://user-images.githubusercontent.com/25195956/104814147-96a2c180-580d-11eb-8e84-35356b0cc7e0.png)
(Make sure you use version 6 when you repack your GARC with `-O version=6`)

**Comment by JokerDKha** [comment]
![image](https://user-images.githubusercontent.com/56380626/104814622-996bd980-5842-11eb-948a-e87ca512c797.png)
Thank's for the support now anything working so fine <3

**Comment by JokerDKha** [comment]
Can you check about this file seem like it error. Im try repack this file and the game crash again.
Location file:
a1-2-5

![image](https://user-images.githubusercontent.com/56380626/104961574-2bbdda00-5a09-11eb-94eb-abdfec1cd846.png)
![dec_2](https://user-images.githubusercontent.com/56380626/104961586-324c5180-5a09-11eb-8b90-f8d425d7629d.png)
[5.zip](https://github.com/Tyulis/3DSkit/files/5832340/5.zip)

**Comment by Tyulis** [comment]
Well, it looks like it’s some sort of custom container that is incorrectly detected as a BFLIM by 3DSkit (hence the weird looping on the image). I think you’ll need to use an hex editor to extract the BFLIM part yourself (everything that is not highlighted here), convert the BFLIM with 3DSkit, edit it, convert it back to BFLIM, and put it back into the file.
![image](https://user-images.githubusercontent.com/25195956/104968205-82192180-59e5-11eb-8aaa-759a36ce9e4d.png)
As it is a custom format with no way to recognize it properly, there is not much I can do, sorry ^^

**Comment by IcySon55** [comment]
That looks like a bad extraction, as if the archive tool has the offsets wrong. :thinking: 

Looks more like it should start at SARC which is a known archive format.

**Comment by JokerDKha** [comment]
> That looks like a bad extraction, as if the archive tool has the offsets wrong. 🤔
> 
> Looks more like it should start at SARC which is a known archive format.

Im try delete First Hex File and extract the SARC. 
![image](https://user-images.githubusercontent.com/56380626/104995818-7109f800-5a59-11eb-8721-5db300b219c3.png)
The file now can extract 
![Common_Grpfont_Icon](https://user-images.githubusercontent.com/56380626/104995682-3e5fff80-5a59-11eb-9265-9f79a8f6aa56.png)
 But now i dont even know how to put it back :(

**Comment by IcySon55** [comment]
Hmm, I know our tools support SARC. Have you heard of Kuriimu? Or perhaps you're asking about how to put it all back in the end, like restoring the stripped bytes before SARC. I haven't looked into these files that deeply so I'm short on details.

How many layers of extraction are we at before getting to the BFLIM? Like how many archives deep are we and what are the filenames and types?

**Comment by JokerDKha** [comment]
> Hmm, I know our tools support SARC. Have you heard of Kuriimu? Or perhaps you're asking about how to put it all back in the end, like restoring the stripped bytes before SARC. I haven't looked into these files that deeply so I'm short on details.
> 
> How many layers of extraction are we at before getting to the BFLIM? Like how many archives deep are we and what are the filenames and types?

Im trying used Kuriimu too but it still error.
Can you check help me check out this file?
Here is the file:
[dec_2.zip](https://github.com/Tyulis/3DSkit/files/5834627/dec_2.zip)

**Comment by Tyulis** [comment]
> Hmm, I know our tools support SARC. Have you heard of Kuriimu? Or perhaps you're asking about how to put it all back in the end, like restoring the stripped bytes before SARC. I haven't looked into these files that deeply so I'm short on details.
> How many layers of extraction are we at before getting to the BFLIM? Like how many archives deep are we and what are the filenames and types?

3DSkit supports SARC as well, but there’s a custom header with no way to recognize it properly, and it is probably only used here.

**Comment by Tyulis** [comment]
> But now i dont even know how to put it back :(

You can directly copy the reconverted file’s content in place of the old one with an hex editor

**Comment by Tyulis** [comment]
> That looks like a bad extraction, as if the archive tool has the offsets wrong. 🤔

It’s not, I double-checked the GARC content and the files are extracted properly

**Comment by JokerDKha** [comment]
> > But now i dont even know how to put it back :(
> 
> You can directly copy the reconverted file’s content in place of the old one with an hex editor

Im use HxD but dont know how to import or replace the file.

**Comment by Tyulis** [comment]
Just replace the original content at the original position by the new one by copy-pasting

**Comment by JokerDKha** [comment]
Copy like that make a files error.
Im use File edit sarc and i copy  original content form old file to new file like this.
![image](https://user-images.githubusercontent.com/56380626/105028177-492f8a00-5a83-11eb-8f9c-751474a1a848.png)

**Comment by Tyulis** [comment]
Are you sure you pasted it at the original position, and that you replaced the original content (by selecting it before pasting such that it is overwritten) ? It should not give you any "file size changed" warning

**Comment by JokerDKha** [comment]
Original File:
![image](https://user-images.githubusercontent.com/56380626/105029103-7a5c8a00-5a84-11eb-8734-fcaf0b53f2a3.png)
Edited File:
![image](https://user-images.githubusercontent.com/56380626/105029165-8b0d0000-5a84-11eb-8fd5-5d67416d3b05.png)

**Comment by Tyulis** [comment]
Ok, so if you’re sure you put the data correctly, what kind of error do you get ?

**Comment by JokerDKha** [comment]
> Ok, so if you’re sure you put the data correctly, what kind of error do you get ?

Im try repack a game with edited file, and the game crash.
The file edited cant extract(3dskit) or view(Kuriimu,SwitchTool) again.

**Comment by Tyulis** [comment]
What’s weird is that I have no problem whatsoever
![image](https://user-images.githubusercontent.com/25195956/105033871-fb9e2780-5a58-11eb-8a05-5f974eb40136.png)

**Comment by Tyulis** [comment]
Oh, I found your problem. I’m trying to fix it, it’s in the pure-python compression part

**Comment by Tyulis** [comment]
It should be fixed by the latest commit

**Comment by JokerDKha** [comment]
Working 100000%
Thank's you <3
![image](https://user-images.githubusercontent.com/56380626/105061130-bce58d00-5aab-11eb-9833-cde26e72311c.png)

**Comment by JokerDKha** [comment]
Sorry for bothering you again but im need help for extract Z-move sprits but i dont know how to open this file and extract it.
Im using 3DSkit and it print like below:
No compression
UnrecognizedFormatError: Unrecognized format (102)
[dec_2.zip](https://github.com/Tyulis/3DSkit/files/7249011/dec_2.zip)

**Comment by Tyulis** [comment]
It seems like a custom texture format, so it’s not supported by 3DSkit
The header mentions a TGA file, but it doesn’t look like one.

**Comment by JokerDKha** [comment]
im find out we can Export with this:
https://gbatemp.net/threads/wip-ultra-sun-and-ultra-moon-pokemon-models-textures-and-animations.490365/ 
But now i dont think this tool will let saving again after editing a picture :(
![image](https://user-images.githubusercontent.com/56380626/135512554-75599155-2791-4adb-a51b-f5565f7b5d76.png)
EDIT:
I find out the way to replace the tex. Tks and sorry bothering you <3

**Comment by IcySon55** [comment]
Hey there guys. Just figured I could chip in here specifically on dec_2.bin.

The image is 3DS Z-Order ETC1A4 encoded, 512 x 256:
![image](https://user-images.githubusercontent.com/4888934/135590990-8354b03d-7fc5-4d62-801d-aaeb1e968e9b.png)

And here's the image saved to PNG:
![dec_2 bin](https://user-images.githubusercontent.com/4888934/135591032-7bfeec7d-5fd0-4556-8e4c-b9ed3db04fc3.png)

The file header leaves much to be desired but an image plugin for this is certainly doable. :)

**Comment by JokerDKha** [comment]
Nice is so good to hear that, if kuriimu have image plugin for this tex. It so easy for edit picture in game.
There is so much file in this game using image is 3DS Z-Order ETC1A4 encoded in game.

**Comment by IcySon55** [comment]
A plugin would need to be created of course, but that shouldn't be that difficult if somebody wants to give it a go. I don't have that much time on my hands these days. ;_;

**Comment by JokerDKha** [comment]
After Edited file with Ohana3DS sun-moon, the file will not working after repack.
Header like below:
Edited:
![1](https://user-images.githubusercontent.com/56380626/135737210-1087c6f5-347a-4059-bd2b-d70c2a923ed7.png)
Original:
![2](https://user-images.githubusercontent.com/56380626/135737211-314f5661-53d2-425c-a455-0e8b49b0c7f1.png)

**Comment by Tyulis** [comment]
Making a 3DSkit module is certainly possible, but this require some investigation on the format first, I’ll try to give it a go today

**Comment by Tyulis** [comment]
The format seems fairly simple, I hacked something together that seems to work.
ETC1 and ETC1A4 compression is not supported yet, but it might work with more standard formats like RGBA4 or RGB5551, could you please check ?

Conversion to PNG is as usual, to convert it back it’s with the `PkmSMTexture` format : 
`3DSkit.py -pf PkmSMTexture -o <output file> -Oformat=<texture format> image.png`

The image file name is important as it is stored inside the file and presumably used to identify it in other models and scenes, so keep the filename given when 3DSkit extracts the file.

**Comment by JokerDKha** [comment]
Report more error big file GARC cant repack
RGB5551 is not support and RGBA4 is not working.
Im try repack with pk3DS
Sample:
https://drive.google.com/file/d/1rC3KI-TYiVoJdPa9d1X1_0uK6bMEIUFP/view?usp=sharing
![error](https://user-images.githubusercontent.com/56380626/135762886-174450ce-c706-4416-a86a-fd0a3df7083c.png)
![packed](https://user-images.githubusercontent.com/56380626/135762884-b648e64b-1551-47b3-b009-a7aeac43afad.png)

**Comment by Tyulis** [comment]
It’s `RGBA5551`, not RGB, sorry for the typo
I just fixed some regressions in the last updates, ensure you use the latest commit.
Don’t forget the `-d` option when packing an archive, otherwise it won’t pack it properly, your error might be because of this.

If repacking in another texture format does not work I’m afraid I won’t have time to implement it any time soon, ETC1 compression is currently not supported and would be much more complicated to implement, and I don’t have free time for that at the moment.

**Comment by JokerDKha** [comment]
RGBA5551 still not working too
Sample file
[ez_cmn_name_02_usa.zip](https://github.com/Tyulis/3DSkit/files/7275151/ez_cmn_name_02_usa.zip)
.

**Comment by Tyulis** [comment]
I could successfully replace one of those ETC1A4 texture in RGBA4 format, so check that you used the right options, did not forget to remove your working files from the GARC directory before packing, did not inadvertantly renamed a file, …
![image](https://user-images.githubusercontent.com/25195956/135896060-f0b082d8-674f-4ac7-a86e-bb58ee364a0f.png)

For reference, the command to convert the texture back : 
`3DSkit.py -pf PkmSMTexture -o whatever\dec_3.bin -Oformat=RGBA4 whatever\ez_cmn_name_03_fra.png`
And to repack the GARC : 
`3DSkit.py -pdf GARC -o 7 -Oversion=6 whatever\7_`

**Comment by IcySon55** [comment]
@Tyulis Regarding replacing textures with other pixel formats. I imagine that your script updated the format identifier in the header accordingly. However, RGBA4 likely produces a larger file and thus eats more VRAM while in-game. I've often seen this cause games to crash because their ram allowance is usually well used by the devs.

In short, I do not recommend changing the pixel format when modifying game graphics. Especially on low-spec hardware like most handhelds.

**Comment by JokerDKha** [comment]
@Tyulis it working so Fine now, but repack GARC is take so long maybe 30-45min.
But thank's for your help, im will update soon if any error show in testing game.

**Comment by Tyulis** [comment]
I know for the memory usage, but I can’t offer a better alternative for the moment ^^
If the memory is well managed the impact with those textures should be relatively minor, but indeed you can’t do this with the ones that are larger and used more often.

**Comment by IcySon55** [comment]
If you want to support ETC1 and many more block compression pixel formats, you can interface with Kontract and Kanvas to get support for those formats without rewriting it in Python. Though I'm not too sure how well Python can even work with C# DLLs. You might have to go through the Kuriimu2 command line executable instead.

~~Or y'know, come write plugins for us, work on the UI and become a part of the team. XD~~
